name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # To load past commits, please set `fetch-depth: 0`
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Make Project
      - name: Build
        run: make